-- Seed formålskoder (from 1400 og Nasjonale feltkoder.xlsx)

INSERT INTO formal_kode (formal_1, formal_2) VALUES
    ('Bebyggelse og anlegg', 'Bebyggelse og anlegg (1001)'),
    ('Bebyggelse og anlegg', 'Boligbebyggelse (1110)'),
    ('Bebyggelse og anlegg', 'Boligbebyggelse, frittliggende småhusbebyggelse (1111)'),
    ('Bebyggelse og anlegg', 'Boligbebyggelse, konsentrert småhusbebyggelse (1112)'),
    ('Bebyggelse og anlegg', 'Boligbebyggelse, blokker (1113)'),
    ('Bebyggelse og anlegg', 'Studentboliger (1114)'),
    ('Bebyggelse og anlegg', 'Garasjeanlegg for bolig- eller fritidsbebyggelse (1119)'),
    ('Bebyggelse og anlegg', 'Fritidsbebyggelse (1120)'),
    ('Bebyggelse og anlegg', 'Frittliggende fritidsbebyggelse (1121)'),
    ('Bebyggelse og anlegg', 'Konsentrert fritidsbebyggelse (1122)'),
    ('Bebyggelse og anlegg', 'Fritidsbebyggelse, blokker (1123)'),
    ('Bebyggelse og anlegg', 'Kolonihage (1124)'),
    ('Bebyggelse og anlegg', 'Sentrumsformål (1130)'),
    ('Bebyggelse og anlegg', 'Kjøpesenter (1140)'),
    ('Bebyggelse og anlegg', 'Forretninger (1150)'),
    ('Bebyggelse og anlegg', 'Bebyggelse for offentlig eller privat tjenesteyting (1160)'),
    ('Bebyggelse og anlegg', 'Barnehage (1161)'),
    ('Bebyggelse og anlegg', 'Undervisning (1162)'),
    ('Bebyggelse og anlegg', 'Forsamlingslokale for tro- og livssynsutøvelse (1164)'),
    ('Bebyggelse og anlegg', 'Forsamlingslokale (1165)'),
    ('Bebyggelse og anlegg', 'Administrasjon (1166)'),
    ('Bebyggelse og anlegg', 'Kulturinstitusjon (1167)'),
    ('Bebyggelse og anlegg', 'Helse-eldreomsorgsinstitusjon (1168)'),
    ('Bebyggelse og anlegg', 'Nærmere angitt offentlig eller privat tjenesteyting (1169)'),
    ('Bebyggelse og anlegg', 'Fritids- og turistformål (1170)'),
    ('Bebyggelse og anlegg', 'Utleiehytter (1171)'),
    ('Bebyggelse og anlegg', 'Fornøyelsespark eller temapark (1172)'),
    ('Bebyggelse og anlegg', 'Campingplass (1173)'),
    ('Bebyggelse og anlegg', 'Leirplass (1174)'),
    ('Bebyggelse og anlegg', 'Råstoffutvinning (1200)'),
    ('Bebyggelse og anlegg', 'Steinbrudd og masseuttak (1201)'),
    ('Bebyggelse og anlegg', 'Massemottak (1202)'),
    ('Bebyggelse og anlegg', 'Næringsbebyggelse (1300)'),
    ('Bebyggelse og anlegg', 'Kontor (1310)'),
    ('Bebyggelse og anlegg', 'Hotell og overnatting (1320)'),
    ('Bebyggelse og anlegg', 'Bevertning (1330)'),
    ('Bebyggelse og anlegg', 'Industri (1340)'),
    ('Bebyggelse og anlegg', 'Kraftkrevende industri (1341)'),
    ('Bebyggelse og anlegg', 'Datasenter (1342)'),
    ('Bebyggelse og anlegg', 'Lager (1350)'),
    ('Bebyggelse og anlegg', 'Bensinstasjon/vegserviceanlegg (1360)'),
    ('Bebyggelse og anlegg', 'Nærmere angitt næring (1390)'),
    ('Bebyggelse og anlegg', 'Idrettsanlegg (1400)'),
    ('Bebyggelse og anlegg', 'Skianlegg (1410)'),
    ('Bebyggelse og anlegg', 'Skiløypetrasé (1420)'),
    ('Bebyggelse og anlegg', 'Idrettsstadion (1430)'),
    ('Bebyggelse og anlegg', 'Nærmiljøanlegg (1440)'),
    ('Bebyggelse og anlegg', 'Golfbane (1450)'),
    ('Bebyggelse og anlegg', 'Motorsportanlegg (1460)'),
    ('Bebyggelse og anlegg', 'Skytebane (1470)'),
    ('Bebyggelse og anlegg', 'Nærmere angitt idrettsanlegg (1490)'),
    ('Bebyggelse og anlegg', 'Andre typer anlegg (1500)'),
    ('Bebyggelse og anlegg', 'Godsterminal (1501)'),
    ('Bebyggelse og anlegg', 'Godslager (1502)'),
    ('Bebyggelse og anlegg', 'Energianlegg (1510)'),
    ('Bebyggelse og anlegg', 'Fjernvarmeanlegg (1520)'),
    ('Bebyggelse og anlegg', 'Vindkraftanlegg (1530)'),
    ('Bebyggelse og anlegg', 'Solkraftanlegg (1531)'),
    ('Bebyggelse og anlegg', 'Vann- og avløpsanlegg (1540)'),
    ('Bebyggelse og anlegg', 'Vannforsyningsanlegg (1541)'),
    ('Bebyggelse og anlegg', 'Avløpsanlegg (1542)'),
    ('Bebyggelse og anlegg', 'Overvannsanlegg (1543)'),
    ('Bebyggelse og anlegg', 'Renovasjonsanlegg (1550)'),
    ('Bebyggelse og anlegg', 'Nærmere angitt kommunalteknisk anlegg (1560)'),
    ('Bebyggelse og anlegg', 'Telekommunikasjonsanlegg (1570)'),
    ('Bebyggelse og anlegg', 'Småbåtanlegg i sjø og vassdrag (1587)'),
    ('Bebyggelse og anlegg', 'Småbåtanlegg i sjø og vassdrag med tilhørende strandsone (1588)'),
    ('Bebyggelse og anlegg', 'Uthus, naust eller badehus (1589)'),
    ('Bebyggelse og anlegg', 'Nærmere angitte andre typer anlegg (1590)'),
    ('Bebyggelse og anlegg', 'Uteoppholdsareal (1600)'),
    ('Bebyggelse og anlegg', 'Lekeplass (1610)'),
    ('Bebyggelse og anlegg', 'Gårdsplass (1620)'),
    ('Bebyggelse og anlegg', 'Parsellhage (1630)'),
    ('Bebyggelse og anlegg', 'Urbant landbruk (1640)'),
    ('Bebyggelse og anlegg', 'Nærmere angitte uteoppholdsarealer (1690)'),
    ('Bebyggelse og anlegg', 'Gravplass (1700)'),
    ('Bebyggelse og anlegg', 'Krematorium (1710)'),
    ('Bebyggelse og anlegg', 'Bygg og anlegg for gravplass (1730)'),
    ('Bebyggelse og anlegg', 'Bebyggelse og anlegg kombinert i samsvar med angitte bestemmelser (1800)'),
    ('Bebyggelse og anlegg', 'Kombinert bolig og forretning (1801)'),
    ('Bebyggelse og anlegg', 'Kombinert bolig, forretning og kontor (1802)'),
    ('Bebyggelse og anlegg', 'Kombinert bolig og tjenesteyting (1803)'),
    ('Bebyggelse og anlegg', 'Kombinert bolig og kontor (1804)'),
    ('Bebyggelse og anlegg', 'Kombinert forretning og kontor (1810)'),
    ('Bebyggelse og anlegg', 'Kombinert forretning, kontor og industri (1811)'),
    ('Bebyggelse og anlegg', 'Kombinert forretning og industri (1812)'),
    ('Bebyggelse og anlegg', 'Kombinert forretning, kontor og tjenesteyting (1813)'),
    ('Bebyggelse og anlegg', 'Kombinert forretning og tjenesteyting (1814)'),
    ('Bebyggelse og anlegg', 'Kombinert næring og tjenesteyting (1824)'),
    ('Bebyggelse og anlegg', 'Kombinert kontor og lager (1825)'),
    ('Bebyggelse og anlegg', 'Kombinert industri og lager (1826)'),
    ('Bebyggelse og anlegg', 'Kombinert kontor og industri (1830)'),
    ('Bebyggelse og anlegg', 'Kombinert kontor og tjenesteyting (1831)'),
    ('Bebyggelse og anlegg', 'Bebyggelse og anlegg kombinert med andre angitte hovedformål (1900)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Samferdselsanlegg og teknisk infrastruktur (arealer) (2001)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Veg (2010)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Kjøreveg (2011)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Fortau (2012)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Torg (2013)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Gatetun (2014)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Gang- og sykkelveg (2015)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Gangveg, gangareal eller gågate (2016)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Sykkelanlegg (2017)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Annen veggrunn, teknisk anlegg (2018)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Annen veggrunn, grøntareal (2019)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Faunapassasje (2200)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Bane (2020)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Jernbane (2021)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Sproveg (2022)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Taubane (2023)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Stasjons- eller terminalbygg (2024)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Holdeplass eller plattform (2025)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Leskur eller plattformtak (2026)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Tekniske bygninger og konstruksjoner (2027)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Annen banegrunn, tekniske anlegg (2028)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Annen banegrunn, grøntareal (2029)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Lufthavn (2030)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Lufthavn, banesystem (2031)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Lufthavn, bygninger (2035)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Landingsplass for helikopter o.a. (2034)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Havn (2040)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Kai (2041)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Havneterminaler (2042)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Havnelager (2043)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Molo (2044)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Navigasjonsinstallasjon (2045)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Hovednett for sykkel (2050)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Kollektivnett (2060)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Trase for nærmere angitt kollektivtransport (2061)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Kollektivknutepunkt (2070)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Kollektivanlegg (2071)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Kollektivterminal (2072)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Kollektivholdeplass (2073)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Pendler- eller innfartsparkering (2074)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Parkering (2080)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Rasteplass (2081)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Parkeringsplasser (2082)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Parkeringshus eller -anlegg (2083)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Teknisk infrastruktur (2101)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Kraftledning, energinett (2110)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Fjernvarmenett (2120)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Vann- og avløpsnett (2140)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Vannforsyningsnett (2141)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Avløpsnett (2142)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Trasé for overvann (2143)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Trasé for avfallssug (2150)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Telekommunikasjonsnett (2160)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Sikringsanlegg (2170)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Trasé for nærmere angitt teknisk infrastruktur (2180)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Kombinerte tekniske infrastrukturtraseer (2190)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Samferdselsanlegg og teknisk infrastruktur kombinert i samsvar med angitte bestemmelser (2800)'),
    ('Samferdselsanlegg og teknisk infrastruktur', 'Samferdselsanlegg eller teknisk infrastruktur kombinert med andre angitte hovedformål (2900)'),
    ('Grønnstruktur', 'Grønnstruktur (3001)'),
    ('Grønnstruktur', 'Blågrønnstruktur (3002)'),
    ('Grønnstruktur', 'Naturområde (3020)'),
    ('Grønnstruktur', 'Turdrag (3030)'),
    ('Grønnstruktur', 'Turveg (3031)'),
    ('Grønnstruktur', 'Friområde (3040)'),
    ('Grønnstruktur', 'Badeplass eller -område (3041)'),
    ('Grønnstruktur', 'Park (3050)'),
    ('Grønnstruktur', 'Vegetasjonsskjerm (3060)'),
    ('Grønnstruktur', 'Vannspeil (3061)'),
    ('Grønnstruktur', 'Overvannstiltak (3100)'),
    ('Grønnstruktur', 'Infiltrasjon, fordrøyning eller avledning (3110)'),
    ('Grønnstruktur', 'Grønnstruktur kombinert i samsvar med angitte bestemmelser (3800)'),
    ('Grønnstruktur', 'Grønnstruktur kombinert med andre angitte hovedformål (3900)'),
    ('Forsvaret', 'Forsvaret (4001)'),
    ('Forsvaret', 'Ulike typer militære formål (4010)'),
    ('Forsvaret', 'Skytefelt eller øvingsområde (4020)'),
    ('Forsvaret', 'Forlegning/leir (4030)'),
    ('Forsvaret', 'Områder for Forsvaret kombinert i samsvar med angitte bestemmelser (4800)'),
    ('Forsvaret', 'Områder for Forsvaret kombinert med andre angitte hovedformål (4900)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'LNFR-areal for nødvendige tiltak for landbruk og reindrift og gårdstilknyttet næringsvirksomhet basert på gårdens ressursgrunnlag (5100)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Landbruksformål (5110)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Jordbruk (5111)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Skogbruk (5112)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Seterområde (5113)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Gartneri (5114)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Naturformål (5120)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Friluftsformål (5130)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Reindrift (5140)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'LNFR-areal for spredt bolig-, fritids- eller næringsbebyggelse mv. (5200)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Spredt boligbebyggelse (5210)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Spredt fritidsbebyggelse (5220)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Spredt næringsbebyggelse (5230)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Naturvern (5300)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Jordvern (5400)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Særlige landskapshensyn (5500)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Vern av kulturmiljø eller kulturminne (5600)'),
    ('Landbruks-, natur og friluftsområder samt reindrift (LNFR)', 'Områder for landbruks-, natur- og friluftsformål samt reindrift (LNFR) kombinert med andre angitte hovedformål (5900)'),
    ('Bruk og vern av sjø og vassdrag', 'Bruk og vern av sjø og vassdrag med tilhørende strandsone (6001)'),
    ('Bruk og vern av sjø og vassdrag', 'Ferdsel (6100)'),
    ('Bruk og vern av sjø og vassdrag', 'Ankringsområde (6110)'),
    ('Bruk og vern av sjø og vassdrag', 'Opplagsområde (6120)'),
    ('Bruk og vern av sjø og vassdrag', 'Riggområde (6130)'),
    ('Bruk og vern av sjø og vassdrag', 'Massedeponi i sjø og vassdrag (6140)'),
    ('Bruk og vern av sjø og vassdrag', 'Farleder (6200)'),
    ('Bruk og vern av sjø og vassdrag', 'Hoved- og biled (6211)'),
    ('Bruk og vern av sjø og vassdrag', 'Havneområde i sjø (6220)'),
    ('Bruk og vern av sjø og vassdrag', 'Småbåthavn (6230)'),
    ('Bruk og vern av sjø og vassdrag', 'Bøyehavn (6240)'),
    ('Bruk og vern av sjø og vassdrag', 'Fiske (6300)'),
    ('Bruk og vern av sjø og vassdrag', 'Fiskeområde (6310)'),
    ('Bruk og vern av sjø og vassdrag', 'Låssettingsplasser (6320)'),
    ('Bruk og vern av sjø og vassdrag', 'Gytefelt eller oppvekstområde for yngel (6330)'),
    ('Bruk og vern av sjø og vassdrag', 'Akvakultur (6400)'),
    ('Bruk og vern av sjø og vassdrag', 'Akvakulturanlegg i sjø og vassdrag (6410)'),
    ('Bruk og vern av sjø og vassdrag', 'Akvakulturanlegg i sjø og vassdrag med tilhørende landanlegg (6420)'),
    ('Bruk og vern av sjø og vassdrag', 'Fangstbasert levendelagring (6430)'),
    ('Bruk og vern av sjø og vassdrag', 'Drikkevann (6500)'),
    ('Bruk og vern av sjø og vassdrag', 'Naturområde i sjø og vassdrag (6610)'),
    ('Bruk og vern av sjø og vassdrag', 'Naturområde i sjø og vassdrag med tilhørende strandsone (6620)'),
    ('Bruk og vern av sjø og vassdrag', 'Friluftsområde i sjø og vassdrag (6710)'),
    ('Bruk og vern av sjø og vassdrag', 'Friluftsområde i sjø og vassdrag med tilhørende strandsone (6720)'),
    ('Bruk og vern av sjø og vassdrag', 'Idrett og vannsport (6760)'),
    ('Bruk og vern av sjø og vassdrag', 'Badeområde (6770)'),
    ('Bruk og vern av sjø og vassdrag', 'Bruk og vern av sjø og vassdrag med tilhørende strandsone kombinert i samsvar med angitte bestemmelser (6800)'),
    ('Bruk og vern av sjø og vassdrag', 'Bruk og vern av sjø og vassdrag med eller uten tilhørende strandsone kombinert med andre angitte hovedformål. (6900)')
ON CONFLICT (formal_1, formal_2) DO NOTHING;
