-- Seed gallery items for each tema_tittel
INSERT INTO tema_tittel_galeri (tema_tittel_id, forklaring, overskrift, bildefilnavn, forklaringstekst, datafelt_type_id, sortering, created_at, updated_at)
VALUES
((SELECT id FROM tema_tittel WHERE navn = 'Dokumentasjon' LIMIT 1), 'Hva er en Dispensasjon?', 'Søke om noe som ikke er lov/dispensasjon', '', 'Hva er en dispensasjon?
Dispensasjon vil si at kommunen gir noen godkjenning i en konkret sak til et tiltak som ellers ville vært ulovlig. Det må sendes en begrunnet søknad om dispensasjon til kommunen.
Loven bygger på et prinsipp om at arealbruk skal styres gjennom de rammer som er vedtatt i plan- og bygningsloven med tilhørende forskrifter og arealplaner (kommuneplaner og reguleringsplaner). Arealplanene har blitt til gjennom omfattende planprosesser som har resultert i politiske vedtak.  I enkelttilfeller kan det likevel være behov for å gjøre unntak. En dispensasjon kan derfor betraktes som en praktisk sikkerhetsventil, men terskelen for å få en dispensasjon er høy.
Kommunen kan gi en dispensasjon dersom hensynene bak bestemmelsen det dispenseres fra, hensynene i lovens formålsbestemmelse eller nasjonale eller regionale interesser ikke blir vesentlig tilsidesatt. Det er også et vilkår at fordelene ved dispensasjonen er klart større enn ulempene.
For mer informasjon må du ta kontakt med kommunen.', NULL, 1, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Funksjon og bruk' LIMIT 1), 'Hva menes med Enebolig?', 'Enebolig', 'TypeBebyggelseEnebolig.png', 'En enebolig er et frittstående hus som er bygget for én husstand. Det står ikke sammen med andre boliger, og har egne yttervegger rundt hele bygningen. 
Eneboliger gir normalt mer privatliv, egen hage og større frihet til utforming enn boliger som er koblet sammen med andre. 
Fritidsbebyggelse
 
Fritidsbebyggelse er bygg som er laget for privat fritidsbruk, og som normalt brukes i kortere perioder av gangen, for eksempel i helger og ferier. Slike bygg kan variere mye i størrelse og standard, fra enkle hytter uten strøm og vann til moderne fritidsboliger med høy komfort. ', NULL, 2, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Funksjon og bruk' LIMIT 1), 'Hva menes med Fritidsbebyggelse?', 'Fritidsbebyggelse', 'TypeBebyggelseFritidsbebyggelse.png', 'Fritidsbebyggelse er bygg som er laget for privat fritidsbruk, og som normalt brukes i kortere perioder av gangen, for eksempel i helger og ferier. Slike bygg kan variere mye i størrelse og standard, fra enkle hytter uten strøm og vann til moderne fritidsboliger med høy komfort.', NULL, 3, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Funksjon og bruk' LIMIT 1), 'Hva menes med Kjedehus?', 'Kjedehus', 'TypeBebyggelseKjedehus.png', 'Et kjedehus består av to eller flere boliger som er knyttet sammen med et mellombygg, for eksempel garasje, carport eller bod. Selve boligene står ikke vegg-i-vegg, men kobler sammen gjennom disse bygningene, slik at de danner en «kjede».
Kjedehus gir følelse av en frittliggende bolig, samtidig som de er bygd sammen med nabohuset gjennom et mindre byggverk. ', NULL, 4, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Funksjon og bruk' LIMIT 1), 'Hva menes med Rekkehus?', 'Rekkehus', 'TypeBebyggelseRekkehus.png', 'Et rekkehus er en bygning som består av tre eller flere boliger som står i én sammenhengende rekke vegg mot vegg. ', NULL, 5, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Funksjon og bruk' LIMIT 1), 'Hva menes med Småhus?', 'Småhus', 'TypeBebyggelseSmahus.png', 'Småhus er mindre boligbygg med inntil tre etasjer og med gesimshøyde ikke over 8 meter og mønehøyde ikke over 9 meter (§29-4 i plan- og bygningsloven).
Småhus kan stå alene eller være bygget sammen, for eksempel: 
•    Eneboliger
•    Rekkehus
•    Kjedehus
•    Tomannsboliger
•    Firemannsboliger
Begrepet brukes ofte i reguleringsplaner og byggesaker for å skille denne typen lav bebyggelse fra blokk- og leilighetsbygg. ', NULL, 6, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Flatt tak med takoppbygg eller inntrukket toppetasje', 'Flatt tak med takoppbygg eller inntrukket toppetasje', 'TakTypeFlattTakMedTakoppbyggEllerInntrukketToppetasje.png', 'Et flatt tak med takoppbygg eller inntrukket toppetasje har en horisontal takflate med en ekstra oppbygd del eller inntrukket etasje.', NULL, 7, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Gavl', 'Gavl', 'BegrepTakGavl.png', 'En gavl er den trekantede veggen du ser i enden av et hus med saltak. Denne veggen følger formen på taket og kalles også gavlvekk. Den er vanligvis en forlengelse av husets endevegg og danne avslutningen på bygningen der takflatene møtes.
Gavlen kan være helt enkel, eller den kan ha vinduer, lufteluker eller dekor, avhengig av byggestil. ', NULL, 8, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Halvvalmet tak', 'Halvvalmet tak', 'TakTypeHalvvalmet.png', 'Et halvvalmet tak er en takform som kombinerer elementer fra både saltak og valmet tak. I stedet for at hele gavlen erstattes av skrå takflater (som på et helvalmet tak), har et halvvalmet tak en mindre skrå valm øverst på gavlveggen.
Det betyr at taket ser ut som et vanlig saltak nederst, men at den øverste delen av gavlen er «kuttet av» og erstattet med en liten skråtakflate. Formen ender ofte i et trapes øverst på gavlveggen.', NULL, 9, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Mansardtak', 'Mansardtak', 'TakTypeMansardtak.png', 'Et mansardstak er en taktype med to skrå takflater på hver side, hvor den nederste flaten er brattere enn den øverste, og ofte har en karakteristisk form som gir ekstra boareal i loftet.', NULL, 10, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Møneretning', 'Møneretning', 'BegrepTakMoneretning.png', '', NULL, 11, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Parapet', 'Parapet', 'TakTypeParapet.png', 'En parapet på et hus er en forlengelse av vegg over takhøyden. Sees oftest på flatt tak. Parapet kan brukes til å skjule mindre takkonstruksjoner eller fall i taket. Parapeten kan for eksempel forme hele eller deler av rekkverket på en takterrasse.  ', NULL, 12, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Pulttak', 'Pulttak', 'TakTypePulttak.png', 'Et pulttak er en skrå taktype som skråner fra den ene siden til det andre over hele takflaten.', NULL, 13, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Saltak', 'Saltak', 'TakTypeSaltak.png', 'Et saltak er en taktype med to skrå takflater som møtes i en møne øverst og danner en trekantform på husets kortsider. Eksempelet viser gesims og møne på saltak.', NULL, 14, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Saltak med tverrfløy', 'Saltak med tverrfløy', 'TakTypeSaltakMedTverrfloy.png', 'Et saltak med tverrfløy har to skrå takflater og en tverrgående fløy.', NULL, 15, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Saltak med tverrfløy og ulik gesims', 'Saltak med tverrfløy og ulik gesims', 'TakTypeSaltakMedTverrfloyOgUlikGesims.png', 'Et saltak med tverrfløy og ulik gesims har to skrå takflater med en tverrfløy, hvor gesimsene (overgangene mellom vegg og tak) varierer i høyde eller stil, og gir et mer komplekst takdesign.', NULL, 16, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Tak med altan i skrå flate', 'Tak med altan i skrå flate', 'TakTypeTakMedAltanSkraFlate.png', 'Et tak med altan i skrå flate har en balkong som er innlemmet i takflaten.', NULL, 17, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Tak med ark', 'Tak med ark', 'TakTypeTakMedArk.png', 'Et tak med ark er et tak med en loftsutbygning med saltak ut fra skråtak.', NULL, 18, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Tak med kobbhus/ark', 'Tak med kobbhus/ark', 'TakTypeTakMedKobbhusArk.png', 'Et tak med ark er et tak med en loftsutbygning med saltak ut fra skråtak.', NULL, 19, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Tak med takopplett', 'Tak med takopplett', 'TakTypeTakMedTakopplett.png', 'Et tak med takopplett har en oppbygd del på toppen av taket.', NULL, 20, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Takvinkel', 'Takvinkel', 'BegrepTakTakvinkel.png', 'Takvinkel, også kalt takhelling, sier hvor bratt et tak er. Det er vinkelen mellom takflaten og et helt vannrett (horisontalt) plan. En høy takvinkel betyr et brattere tak, men en lav takvinkel betyr slakere tak.', NULL, 21, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> To flate takflater', 'To flate takflater', 'TakTypeToFlateTakflater.png', 'Et tak med to flate tak består av to parallelle, horisontale flater.', NULL, 22, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> To takflater/sammensatte pulttak', 'To takflater/sammensatte pulttak', 'TakTypeToTakflaterSammensattePulttak.png', 'Sammensatte pulttak kombinerer flere pulttak med ulike skråninger og høyder.', NULL, 23, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Takform --> Valmtak', 'Valmtak', 'TakTypeValmtak.png', 'Et valmtak er en taktype med skrå takflater på alle fire sider. Eksmpelet viser møne og gesims på valmtak.', NULL, 24, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Bygningers interne utforming' LIMIT 1), 'Utforming --> Møne og gesims', 'Møne og gesims', 'BegrepUtformingMoneOgGesims.png', 'Mønet refererer til den høyeste delen av et tak hvor de to skrå takflatene møtes, og danner en linje som går fra den ene enden av taket til den andre. Denne delen er ofte synlig som en toppkant og kan være både rett og buet, avhengig av takets form.
Gesims er en horisontal utstikkende del av en vegg eller et tak, plassert der taket møter veggen. Gesims fungerer både som en dekorativ detalj og som beskyttelse mot vann som renner ned fra taket.', NULL, 25, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Bebygd areal - BYA - før 1. juli 2007', 'Bebygd areal - BYA - før 1. juli 2007', 'TypeUtnyttelsesgradBebygdarealBYAFor1Juli2007.png', 'Bebygd areal (BYA) er summen av det areal som bebyggelsen opptar av terrenget. BYA måles fra utsiden av ytterveggen.
Det er viktig at du husker å regne med åpne overbygde areal, utkragede bygningsdeler og deler plassert 0,5 meter over terreng. For mer informasjon, se Direktoratet for byggkvalitets veileder "Hva er bebygd areal?"', NULL, 26, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Bebygd areal - etter 1. juli 2007 (BYA)', 'Bebygd areal - etter 1. juli 2007 (BYA)', 'TypeUtnyttelsesgradBebygdarealEtter1Juli2007BYA.png', 'I reguleringsplaner vedtatt etter 1. juli 2007 betyr bebygd areal (BYA) summen av det areal som bebyggelsen opptar av terrenget. BYA måles fra utsiden av ytterveggen.
For mer informasjon, se Direktoratet for byggkvalitets nettside «Hva er bebygd areal?»', NULL, 27, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Bruksareal - BRA - etter 1.7.1997', 'Bruksareal - BRA - etter 1.7.1997', 'TypeUtnyttelsesgradBruksarealBRAEtter1Juli1997.png', 'BRA (bruksareal) er et begrep som beskriver det totale arealet inne i en bygning som kan brukes, målt innenfor bygningens yttervegger. Det finnes to tolkninger av BRA, en før og en etter 1997, og for din eiendom er det den eldre tolkningen som er gjeldende. Bruksarealet gir en oversikt over hvor mye plass som er tilgjengelig til for eksempel bolig eller andre formål.
 
Slik måler du BRA (markert med gult):
Du skal ikke ta med ytterveggene. Alle typer rom skal måles, selv om de ikke er innredet eller kan bebos.
Slik måler du bruksareal på loftet: 
Åpne arealer med tak (overbygg), for eksempel carport, skal måles innenfor søylene.
Når du skal måle, skal du bruke arealet hvor takhøyden innendørs er 1,9 meter eller mer. Hvis taket skråner, skal du legge til 0,6 meter til siden fra punktet hvor takhøyden er nøyaktig 1,9 meter. Dette gjelder også der det er gjort takoppbygg. Måling av loft avhenger av takkonstruksjon.
Slik måler du areal som er helt eller delvis under terreng (sokkel eller kjeller):
Planbestemmelsene for din eiendom avgjør om du skal måle med areal som ligger helt eller delvis under terreng. Det er vanligst at det skal være med. Om det ikke står noe spesielt, skal du måle det. Det er spesifikke regler for hvordan areal under terreng skal måles.
Om det står at areal helt eller delvis ikke skal være med, trenger du ikke måle det. For mer informasjon, se Direktoratet for byggkvalitets veileder «Dette er bruksareal» ', NULL, 28, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Bruttoareal - BRA. Før 1. juli 1997', 'Bruttoareal - BRA. Før 1. juli 1997', 'TypeUtnyttelsesgradBruttoarealBRAFor1Juli1997.png', 'Bruksareal er alle målbare plan inne i bygningen, pluss åpne arealer med overbygg (som carport eller lignende). For mer informasjon, se Direktoratet for byggkvalitets veileder «Dette er bruksareal »', NULL, 29, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Hva menes med Kvadratmeter bruksareal (m2-BRA)?', 'm2-BRA', '', 'Bruksareal for bebyggelse på en tomt skrives i kvadratmeter og forkortes til m²-BRA. Bruksareal for bebyggelse på en tomt setter en øvre grense for det samlede bruksareal for bygninger, åpent overbygd areal og parkeringsareal som er tillatt på en tomt.', NULL, 30, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Hva menes med Tillatt Bruksareal (T-BRA)?', 'T-BRA', '', 'T-BRA er forkortelse for tillatt bruksareal og skrives i kvadratmeter. Tillat bruksareal setter en øvre på hvor stort et byggeprosjekt kan være. T-BRA brukes for å styre størrelsen på bebyggelse for eksempel i områder med ulike størrelser på tomter, for eksempel i hytteområder. En finner T-BRA i eldre reguleringsplaner.  ', NULL, 31, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Hva menes med Tomtutnyttelse (TU)?', 'TU', '', 'Tomteutnyttelse. Dette begrepet brukes vanligvis som %-TU, der prosenten beskiver foholdet mellom tomtestørrelse og bruksareal. ', NULL, 32, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Hva menes med Utnyttelsesgrad?', 'Utnyttelsesgrad av eiendom', '', 'Utnyttelsesgrad av eiendom er et begrep som beskriver hvor stor del av en eiendom som kan bebygges, og hvor mye areal som kan brukes til bebyggelse i forhold til eiendommens totale størrelse. Det gir en oversikt over hvor mye areal som kan brukes til bygging av for eksempel boliger eller andre konstruksjoner på tomten. Utnyttelsesgraden er viktig for å sikre balansert og bærekraftig utbygging, slik at det ikke bygges for tett eller massivt på en tomt, og for å sikre at det er tilstrekkelig utearealer og lysforhold rundt bygningene. Det finnes ulike måter å beregne utnyttelsesgraden på, avhengig av hva slags eiendom det gjelder og hvilke planbestemmelser som gjelder.', NULL, 33, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Hva menes med Prosent av bebygd areal (%BYA)?', 'Prosent bebygd areal - %BYA', 'TypeUtnyttelsesgradProsentBYA.png', 'Prosent av bebygd areal på en tomt forkortes %-BYA. Det brukes til å angi den prosentvise størrelsen en bygning utgjør på en tomt og hvor stor del av tomten som er ubebygd. I mange kommunale planbestemmelser er det en øvre grense for hvor stort man kan bygge på en tomt. Dette er ofte oppgitt i %-BYA, for eksempel maksimalt 20 %-BYA.
For mer informasjon, se side 24 i veilederen “Grad av utnytting”', NULL, 34, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Hva menes med Prosent tomteutnyttelse (%-TU)?', 'Grad av utnytting: %-TU', '', 'Prosent tomteutnyttelse (skrives %-TU) er bruksarealet av tomtas areal, og regulerer forholdet mellom bruksareal av bygninger og tomtearealet. En kan derfor bygge større bygninger på større eiendommer, der grad av utnytting er definert som %-TU. Det kan resultere i et bygg med større grunnflate i en etasje eller mindre grunnflate hvis bygget er høyere. Merk at det sannsynligvis vil være begrensinger i bestemmelsene for byggehøyde, ellers gjelder høydebegrensningene i plan- og bygningslovens § 29-4 (gesims= ≤8 meter og mønehøyde  ≤ 9 meter).', NULL, 35, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Grad av utnytting' LIMIT 1), 'Hva menes med Bebygd areal i kvadratkilometer (BYA-km2)?', 'BYA km2', '', 'BYA km² står for bebygd areal i kvadratkilometer, og brukes typisk når man skal beskrive det samlede bebygde arealet over et større område, som en hel by, region eller land, i stedet for en enkelt tomt.', NULL, 36, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Hensyn/restriksjoner' LIMIT 1), 'Frisiktsone', 'Frisiktsone', 'BegrepVeiFrisiktsone.png', 'Om du eier eller bor i en eiendom med avkjørsel som går til vei, eller over fortau eller gang- og sykkelvei har du ansvar for å sørge for fri sikt ved din avkjørsel og mot veikryss. Du må sørge for at gjerder og beplantning er så lav at alle kan gå, sykle og kjøre trygt forbi eiendommen din. Du kan klippe hekken din slik at den er lavere enn 0,5 meter, eller plassere gjerdet eller hekken utenfor frisiktsonen. Hvor stor frisiktssonen må være avhenger av om det er gang- og sykkelvei eller om avkjørselen din ender i vei. Hvis den ender i en vei, er det fartsgrensen på veien som avgjør hvor stor frisiktsonen må være. ', NULL, 37, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Hensyn/restriksjoner' LIMIT 1), 'Hensynssone', 'Hensynssone', 'BegrepNokkelinformasjonHensynssone.png', 'En hensynssone er et område i en kommuneplan elle reguleringsplan hvor det gjelder særlige hensyn eller restriksjoner. Hensynet eller restriksjonen gjelder i tillegg til de arealformålene som området er avsatt til. Hensynssoner brukes for å vise områder som krever ekstra oppmerksomhet når man planlegger eller behandler byggesaker.
Slike soner kan for eksempel være områder med:
•    Fare for ras, skred, flom etc. 
•    Støy
•    Kulturminner eller naturverdier
•    Infrastruktur som må tas hensyn til 
•    Behov for felles planlegging før utbygging
Hensynssoner gjør det tydelig for både kommune, grunneiere og utbyggere hva man må ta spesielt hensyn til. Ofte følger det bestemmelser eller retningslinjer som kun gjelder innenfor sonen.', NULL, 38, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Høyder' LIMIT 1), 'Hva menes med Byggehøyde = kotehøyde?', 'Byggehøyde = kotehøyde', 'BegrepHoydeByggehoydeKotehoyde.png', '', NULL, 39, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Høyder' LIMIT 1), 'Hva menes med Halvparten av bygningens største høyde?', 'Halvparten av bygningens største høyde', '', 'Halvparten av bygningens største høyde refererer til en måling som er halvparten av den totale høyden på bygningen fra bakkenivå til det høyeste punktet på bygningen. Dette er relevant der ikke avstand til naboens eiendomsgrense er definert i regulerinsgplanen. Hensikten er at bygg ikke skal plasseres for nærme hverandre. Vurderingen kan også være nyttig i ulike sammenhenger, som for eksempel å beregne skyggeeffekter, planlegging av solcellepaneler, eller for å overholde lokale bygningsforskrifter.', NULL, 40, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Høyder' LIMIT 1), 'Hva menes med Kotehøyde + byggehøyde?', 'Kotehøyde + byggehøyde', 'BegrepHoydeKotehoydeByggehoyde.png', '', NULL, 41, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Høyder' LIMIT 1), 'Hva menes med Møne- og gesimshøyde?', 'Møne- og gesimshøyde', 'BegrepHoydeMoneOgGesimshoyde.png', 'Mønet refererer til den høyeste delen av et tak hvor de to skrå takflatene møtes, og danner en linje som går fra den ene enden av taket til den andre. Gesims, derimot, er en horisontal utstikkende del av en vegg eller et tak, plassert der taket møter veggen. Gesims fungerer både som en dekorativ detalj og som beskyttelse mot vann som renner ned fra taket, og kan bidra til å fremheve bygningens stil og karakter. ', NULL, 42, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Høyder' LIMIT 1), 'Hva menes med Mønehøyde?', 'Mønehøyde', 'BegrepHoydeMonehoyde.png', 'Mønehøyden er høyden til skjæringen mellom to skrå takflater. Mønehøyden måles i forhold til ferdig planert terrengs gjennomsnittsnivå rundt bygningen.
For mer informasjon, se https://www.dibk.no/regelverk/byggteknisk-forskrift-tek17/6/6-', NULL, 43, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Grenser --> Avstand til vei - når byggegrenser ikke er fastsatt', 'Avstand til vei - når byggegrenser ikke er fastsatt', 'TypeGrenseAvstandTilVeiNarByggegrenserIkkeErFastsatt.png', 'Siden det ikke er fastsatt byggegrenser i reguleringsplanen som gjelder for din eiendom eller i kommuneplanen, er det veglovens generelle byggegrenser som gjelder. Veglovens byggegrenser måles fra midten av veien: 50m fra riksvei og fylkesvei, og 15m fra kommunalvei, og gang- og sykkelvei.', NULL, 44, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Grenser --> Byggegrense', 'Byggegrense', 'TypeGrenseByggegrense.png', 'En byggegrense sier hvor på eiendommen din du kan bygge. Byggegrensen vises med stiplet linje på reguleringskartet for eiendommen din. Garasjer og andre mindre byggverk kan i noen tilfeller plasseres nærmere nabogrense, dette er ofte skrevet i planbestemmelsene som gjelder for din eiendom. Hvis du er i tvil, ta kontakt med kommunen for å høre hva som gjelder for din tomt.', NULL, 45, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Grenser --> Byggegrense mot sjø', 'Byggegrense mot sjø', 'TypeGrenseByggegrenseMotSjo.png', '', NULL, 46, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Grenser --> Byggegrense mot vei', 'Byggegrense mot vei', '', 'Hvis byggegrensen mot vei ikke er fastsatt i reguleringsplan eller i bestemmelser til kommuneplanens arealdel, gjelder veglovens generelle byggegrenser. Veglovens byggegrenser måles fra midten av veien:
50 meter til riksvei
50 meter fra fylkesvei
15 meter fra kommunal vei
15 meter fra gang- og sykkelvei
Disse grensene kan være ulike avhengig av hvilket år reguleringsplanen som gjelder for din eiendom ble vedtatt. Ved å følge lenken under kan du finne tabellen på siden til å finne ut hvilke avstander som gjelder for deg. Lenke: https://www.vegvesen.no/trafikkinformasjon/langs-veien/soknad-om-dispensasjon-fra-byggegrenser/dette-ma-du-tenke-pa/', NULL, 47, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Grenser --> Eiendomsgrense', 'Eiendomsgrense', 'TypeGrenseEiendomsgrense.png', 'Eiendomsgrensen viser hvor eiendommen din slutter, og hvor naboens eller et fellesområde begynner. Den forteller altså hvilket område du eier og har ansvar for. Eiendomsgrensen mellom to eiendommer kalles ofte for en nabogrense. Det er i din og naboens interesse å holde rede på hvor eiendomsgrensen går.
Eiendomsgrensene er viktige når du skal bygge, sette opp et gjerde, eller bruke tomta di på andre måter. Eiendomsgrensene vises vanligvis med grensemerker i terrenget og skal i utgangspunktet framgå av matrikkelen og offentlige kart. I noen tilfeller kan det være nødvendig å finne fram gamle dokumenter, for eksempel gamle kart eller skylddelingsforretninger, for å få informasjon om hvor grensen kan gå. Dersom grensene er uklare, kan du bestille oppmålingsforretning av kommunen for å få merket og kartlagt grensen på nytt. Er du uenig med naboen om hvor grensen går, og dere ikke klarer å bli enig, må du eventuelt bringe spørsmålet inn for retten for å få en avgjørelse. ', NULL, 48, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Grenser --> Formålsgrense', 'Formålsgrense', 'TypeGrenseFormalsgrense.png', 'Kommuneplanens arealdel og reguleringsplanen viser hvilke formål et område er ment å brukes til, for eksempel bolig, vei, friområde, næring eller landbruk. Hvert formål avgrenses med en formålsgrense.
Formålsgrensene følger ikke nødvendigvis de enkelte eiendomsgrensene. Det er ikke uvanlig at en eiendom kan være avsatt til flere ulike formål. Det betyr at forskjellige deler av eiendommen kan ha ulike regler og begrensninger.
Et eksempel kan være en eiendom der én del er regulert til bolig, mens en annen del er regulert til veiformål eller grøntareal. Da gjelder reglene for hvert formål kun innenfor sin egen formålsgrense. ', NULL, 49, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Grenser --> Plangrense', 'Plangrense', 'TypeGrensePlangrense.png', 'En plangrense er en linje på et kart som viser hvilket område en plan gjelder for. Den markerer hvor den aktuelle kommuneplanen eller reguleringsplanen slutter, og avgrenser hvilket areal som er omfattet av planens regler.
Alt innenfor plangrensen er styrt av planens bestemmelser, for eksempel om bygging, bruk og vern av areal, og tillatt grad av utnytting. Områdene utenfor plangrensen følger andre regler eller andre planer.
Plangrensen gjør det enkelte å se: 
•    Hvilket område planen gjelder for
•    Hvilke eiendommer som er berørt
•    Hvordan reguleringsformål og bestemmelser skal forstås ', NULL, 50, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Grenser --> Tomtegrense', 'Tomtegrense', '', 'Med tomt menes eiendommens utbyggbare areal. Areal avsatt til for eksempel offentlig vegareal inngår ikke i tomtearealet. Tomtegrensen svarer i utgangspunktet til eiendomsgrensen, men slik at tomtegrensen følger formålsgrensen for eksempel mot offentlig veg dersom deler av eiendommen er avsatt til offentlig vegareal. ', NULL, 51, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Grenser --> Veglovens generelle byggegrenser', 'Veglovens generelle byggegrenser', 'TypeGrenseVeglovensGenerelleByggegrenser.png', 'Siden byggegrensen ikke er fastsatt i reguleringsplan eller i bestemmelser til kommuneplanens arealdel, gjelder veglovens generelle byggegrenser. Ettersom denne loven har blitt endret siden den tredde i kraft i 1913, må du først finne ut hvilket år reguleringsplanen som gjelder deg ble vedtatt. Deretter bruker du tabellen til å finne ut hvilke avstander som gjelder for deg.
For mer informasjon kan du se Vegvesenets nettsider.', NULL, 52, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Hva menes med Balkong?', 'Balkong', 'TypeTiltakBalkong.png', 'En balkong stikker ut fra bygningen og er en del som henger på utsiden av huset. Den festes enten til bjelkene mellom etasjene, eller henges utenpå veggen og støttes av skråstag. Balkonger har ikke søyler eller annen støtte ned til bakken, og gulvet ligger vanligvis på samme nivå som rommet innenfor (eller litt lavere).
Skal du bygge balkong?
Da må du søke kommunen om tillatelse. En balkong påvirker bygningens bæresystem fordi den enten festes inn i konstruksjonen eller henges utenpå. Derfor er både planlegging og bygging mer krevende enn for en enkel veranda eller et lite tilbygg med egne søyler. Det er krav om at en ansvarlig søker (et profesjonelt firma) sender inn søknaden for deg, og at du bruker kvalifiserte fagfolk med ansvarsrett til å utføre arbeidet slik at det gjøres i tråd med regelverket.', NULL, 53, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Hva menes med Platting?', 'Platting', 'TypeTiltakPlatting.png', 'En platting er en enkel, lav konstruksjon, ofte laget av tre. Den ligger gjerne rett på bakken eller på noen små fundamenter. En platting har vanligvis bare ett nivå, og derfor trenger den ikke trapp.
Som regel kan du bygge en platting uten å søke, men kommunen kan ha egne regler i kommune- eller reguleringsplanen som du må sjekke før du setter i gang. For bygging langs vann og sjø og i sårbare områder gjelder strenge regler. Planlegger du å bygge i slike områder, må du alltid sjekke med kommunen på forhånd om det er tillatt.
For at en konstruksjon skal regnes som en platting, kan den ikke være høyere enn 0,5 meter over terrenget. Du kan bygge helt inntil nabogrensa, men det er alltid lurt å snakke med naboen først, det skaper bedre naboskap og gir mulighet for dialog før du bygger.', NULL, 54, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Hva menes med Sokkelleilighet?', 'Sokkelleilighet', 'TypeTiltakSokkelleilighet.png', 'En sokkelleilighet er en egen boenhet som ligger i en sokkeletasje, altså en underetasje der minst én side av bygningen ligger over bakken og vender ut mot åpent terreng. Det betyr at leiligheten får godt med dagslys og ofte har egen inngang på den siden som ligger over terrenget.
Til forskjell fra en kjeller, som stort sett ligger under bakken, har en sokkeletasje en høyere grunnmur og større, normale vinduer på den åpne siden. Derfor kan den brukes som en boenhet med gode lys- og boforhold.', NULL, 55, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Hva menes med Terasse?', 'Terrasse', 'TypeTiltakTerrasse.png', 'En terrasse er et avgrenset uteområde på bakken. Den har vanligvis tilgang både fra huset og videre ut i hagen. Terrassen avgrenses ofte med rekkverk eller en støttemur. Ofte ligger gulvet på terrassen på omtrent samme nivå som gulvet inne i huset.
 
I mange tilfeller kan du bygge terrasse uten å søke, så lenge du følger disse kravene:
•    Terrassen er maks 1 meter over terrenget
•    Rekkverket er maks 1,2 meter høyt
•    Terrassen stikker mindre enn 4 meter ut fra husveggen
•    Terrassen bygges uten tak og egne vegger
•    Du holder minst 1 meter avstand til nabogrensa
•    Du har nok ledig areal på tomta, slik at du ikke overstiger utnyttelsesgraden
 
I tillegg kan det være satt andre begrensninger i kommune- eller reguleringsplan. Før du begynner å bygge, må du derfor sjekke reguleringsplanen for eiendommen din, i tilfelle den har egne begrensninger for hva du kan bygge. For bygging langs vann og sjø og i sårbare områder gjelder strenge regler. Planlegger du å bygge i slike områder, må du alltid sjekke med kommunen på forhånd om det er tillatt.
 
Husk at terrassens høyde over terrenget avgjør hva som regnes som bebygd areal (BYA). Den delen av terrassen som er høyere enn 0,5 meter over gjennomsnittsnivået på det planerte terrenget, skal regnes som BYA og vil inngå i beregningen av tomtens grad av utnytting.
 
Direktoratet for byggkvalitet (DiBK) har en nyttig veiviser som du kan følge: https://www.dibk.no/verktoy-og-veivisere/bygg-uten-a-soke-tilbygg', NULL, 56, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Hva menes med Underetasje?', 'Underetasje', 'TypeTiltakUnderetasje.png', 'En underetasje er en etasje som ligger delvis under bakken fordi huset står i skrånende terreng. Det betyr at den ene delen av etasjen kan være godt synlig over bakken, mens den andre delen ligger lenger ned i terrenget.
For å regnes som underetasje, må innvendig himling i gjennomsnitt ligge mellom 0,75 og 1,5 meter over ferdig terreng rundt bygningen.
En underetasje brukes ofte til oppholdsrom som stue, soverom eller hybel, nettopp fordi deler av etasjen ligger høyt nok til at man får gode lysforhold og normale vinduer.', NULL, 57, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Plassering/Orientering' LIMIT 1), 'Hva menes med Veranda?', 'Veranda', 'TypeTiltakVeranda.png', 'En veranda er en overbygd uteplass som står på støttepunkter, for eksempel søyler. Den kan ha tette vegger eller være kledd med glass, og den kan ligge i alle etasjer. Vanligvis kommer man ut på verandaen fra innsiden av huset.
Du kan bygge en veranda uten å søke, så lenge den:
•    er maks fem meter over bakken
•    er på maks fem kvadratmeter
•    og du har nok ledig areal på tomten slik at du ikke overstiger tillatt grad av utnytting
I tillegg må verandaen stå minst fire meter fra nabogrensen.
I tillegg kan det være satt andre begrensninger i kommune- eller reguleringsplan. Før du begynner å bygge, må du derfor sjekke reguleringsplanen for eiendommen din, i tilfelle den har egne begrensninger for hva du kan bygge. For bygging langs vann og sjø og i sårbare områder gjelder strenge regler. Planlegger du å bygge i slike områder, må du alltid sjekke med kommunen på forhånd om det er tillatt.
Hvis verandaen ikke har støtte under og festes direkte i husveggen, regnes den som en balkong, og da må du søke før du bygger.', NULL, 58, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Teknisk infrastruktur' LIMIT 1), 'Innkjøring parallelt til vei', 'Innkjøring parallelt til vei', 'TypeAvkjorselInnkjoringParalleltTilVei.png', 'Noen reguleringsplaner tillater at innkjøring til tomten går parallelt med veien. Det er typisk et avstandskrav mellom tomtegrensen og garasjen.  Kommunen kan også stille krav om at løsningen ikke legger opp til at man rygger ut i veien, altså at du må ha mulighet til å snu på egen tomt som vist på illustrasjonen. ', NULL, 59, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Teknisk infrastruktur' LIMIT 1), 'Innkjøring rett på vei (90grader)', 'Innkjøring rett på vei (90grader)', 'TypeAvkjorselInnkjoringRettPaVei.png', 'Noen reguleringsplaner har krav om at innkjøring til tomten går 90 grader fra veien. Det er typisk et avstandskrav mellom tomtegrensen og garasjen.  Kommunen kan også stille krav om at løsningen ikke legger opp til at man rygger ut i veien, altså at du må ha mulighet til å snu på egen tomt som vist på illustrasjonen. ', NULL, 60, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Uteområder' LIMIT 1), 'Ferdig planert terreng', 'Ferdig planert terreng', 'BegrepTerrengFerdigPlanertTerreng.png', 'Ferdig planert terrengs gjennomsnittsnivå finner en ved å: Summere kotehøydene i hvert hushjørne og dele på de fire hjørnene. Kotehøydene finner du i detaljerte kart hos kommunen.', NULL, 61, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Uteområder' LIMIT 1), 'Gjennomsnittlig planert terreng', 'Gjennomsnittlig planert terreng', 'BegrepTerrengGjennomsnittligPlanertTerreng.jpg', 'Gjennomsnitlig planert terreng refererer til den gjennomsnittlige høyden på terrenget rundt en bygning etter at det er ferdig utgravd, tilfylt eller på annen måte omdannet under byggeprosessen. Dette nivået brukes ofte som referansepunkt for å måle bygningers høyde, som gesimshøyde og mønehøyde
Beregning av gjennomsnittlig planert terreng
For bygninger på tomter med lite eller jevnt fall, vil det normalt være tilstrekkelig å fastsette kotehøyden på planert terreng i hvert hjørne av bygningen og beregne gjennomsnittet.
Eksempel på beregning av gjennomsnittlig kotehøyde: Gjennomsnittlig kotehøyde = (kote A + kote B + kote C + kote D) / 4. (Du summerer kotehøydene i hvert hushjørne og deler på fire. Kotehøydene finner du i detaljerte kart hos kommunen.)', NULL, 62, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Uteområder' LIMIT 1), 'Hva menes med Murkrone?', 'Murkrone', 'TypeMurMurkrone.png', 'En murkrone er den øverste avslutningen på en mur. Den har to viktige funksjoner: 
•    Beskytte muren mot vann, slik at regn ikke trenger ned i konstruksjonen og skaper frostskader eller sprekker
•    Gi muren et pent og ferdig utseende
Murkronen kan være laget av stein, betong, naturstein eller metall, og den lages ofte med en liten helling slik at vann renner bort fra muren. På støttemurer og hagemurer kan murkronen også fungere som en praktisk sittekant eller avgrensning.', NULL, 63, NOW(), NOW()),
((SELECT id FROM tema_tittel WHERE navn = 'Uteområder' LIMIT 1), 'Måle høyde fra gjennomsnittlig terrengnivå', 'Måle høyde fra gjennomsnittlig terrengnivå', 'BegrepTerrengMaleHoydeFraGjennomsnittligTerrengniva.jpg', 'Høyde fra gjennomsnittlig terrengnivå refererer til målingen av en bygning eller struktur fra det gjennomsnittlige nivået av det ferdig planerte terrenget rundt bygget. Dette er viktig for å sikre at bygninger ikke overstiger tillatte høyder og for å opprettholde en harmonisk bygningsmasse i et område.
Beregning av gjennomsnittlig terreng
For bygninger på tomter med lite eller jevnt fall, vil det normalt være tilstrekkelig å fastsette kotehøyden på planert terreng i hvert hjørne av bygningen og beregne gjennomsnittet.
Eksempel på beregning av gjennomsnittlig kotehøyde: Gjennomsnittlig kotehøyde = (kote A + kote B + kote C + kote D) / 4. (Du summerer kotehøydene i hvert hushjørne og deler på fire. Kotehøydene finner du i detaljerte kart hos kommunen.)
Dette gjennomsnittlige nivået brukes som referansepunkt for å måle både gesimshøyde (høyden til skjæringspunktet mellom ytterveggens ytre flate og takflaten) og mønehøyde (høyden til skjæringspunktet mellom to skrå takflater).', NULL, 64, NOW(), NOW());