# Generated by Django 5.1.7 on 2026-03-11 10:25

import cms_app.models
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='KommuneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('primary_color', models.CharField(default='#000000', max_length=7, validators=[cms_app.models.validate_hex_color])),
                ('secondary_color', models.CharField(default='#000000', max_length=7, validators=[cms_app.models.validate_hex_color])),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_website', models.URLField()),
                ('visiting_address_line1', models.CharField(blank=True, help_text='Gateadresse, f.eks. Rådhusgata 18', max_length=200)),
                ('visiting_address_line2', models.CharField(blank=True, help_text='Postnummer og sted, f.eks. 4604 Kristiansand', max_length=200)),
                ('opening_hours', wagtail.fields.StreamField([('periode', 4)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Mandag', 'Mandag'), ('Tirsdag', 'Tirsdag'), ('Onsdag', 'Onsdag'), ('Torsdag', 'Torsdag'), ('Fredag', 'Fredag'), ('Lørdag', 'Lørdag'), ('Søndag', 'Søndag')], 'label': 'Fra dag'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Mandag', 'Mandag'), ('Tirsdag', 'Tirsdag'), ('Onsdag', 'Onsdag'), ('Torsdag', 'Torsdag'), ('Fredag', 'Fredag'), ('Lørdag', 'Lørdag'), ('Søndag', 'Søndag')], 'label': 'Til dag'}), 2: ('wagtail.blocks.TimeBlock', (), {'label': 'Åpner'}), 3: ('wagtail.blocks.TimeBlock', (), {'label': 'Stenger'}), 4: ('wagtail.blocks.StructBlock', [[('fra_dag', 0), ('til_dag', 1), ('apner', 2), ('stenger', 3)]], {'label': 'Åpningstid'})})),
                ('org_number', models.CharField(max_length=20)),
                ('welcome_message', models.CharField(blank=True, max_length=500)),
                ('links', wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1)]], {})})),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Kommune-konfigurasjon',
                'verbose_name_plural': 'Kommune-konfigurasjoner',
            },
        ),
    ]
