# Generated by Django 5.1.7 on 2026-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE cms_app_kommuneconfig
                    ADD COLUMN IF NOT EXISTS tooltip_property_area text NOT NULL
                    DEFAULT 'Totalt registrert areal for eiendommen.';
                    """,
                    reverse_sql="""
                    ALTER TABLE cms_app_kommuneconfig
                    DROP COLUMN IF EXISTS tooltip_property_area;
                    """,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE cms_app_kommuneconfig
                    ADD COLUMN IF NOT EXISTS tooltip_gnr text NOT NULL
                    DEFAULT 'Hovednummer som identifiserer gården i matrikkelen.';
                    """,
                    reverse_sql="""
                    ALTER TABLE cms_app_kommuneconfig
                    DROP COLUMN IF EXISTS tooltip_gnr;
                    """,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE cms_app_kommuneconfig
                    ADD COLUMN IF NOT EXISTS tooltip_bnr text NOT NULL
                    DEFAULT 'Undernummer for den enkelte eiendom under gårdsnummeret.';
                    """,
                    reverse_sql="""
                    ALTER TABLE cms_app_kommuneconfig
                    DROP COLUMN IF EXISTS tooltip_bnr;
                    """,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE cms_app_kommuneconfig
                    ADD COLUMN IF NOT EXISTS tooltip_fnr text NOT NULL
                    DEFAULT 'Nummer for festetomt under gårdsnummeret.';
                    """,
                    reverse_sql="""
                    ALTER TABLE cms_app_kommuneconfig
                    DROP COLUMN IF EXISTS tooltip_fnr;
                    """,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE cms_app_kommuneconfig
                    ADD COLUMN IF NOT EXISTS tooltip_snr text NOT NULL
                    DEFAULT 'Nummer som identifiserer seksjonen i en seksjonert eiendom.';
                    """,
                    reverse_sql="""
                    ALTER TABLE cms_app_kommuneconfig
                    DROP COLUMN IF EXISTS tooltip_snr;
                    """,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE cms_app_kommuneconfig
                    ADD COLUMN IF NOT EXISTS tooltip_eierbrok text NOT NULL
                    DEFAULT 'Eierandel uttrykt som brøkdel av eiendommen.';
                    """,
                    reverse_sql="""
                    ALTER TABLE cms_app_kommuneconfig
                    DROP COLUMN IF EXISTS tooltip_eierbrok;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='kommuneconfig',
                    name='tooltip_bnr',
                    field=models.TextField(blank=True, default='Undernummer for den enkelte eiendom under gårdsnummeret.', help_text='Vises ved siden av «Bruksnummer» i eiendomskortet.'),
                ),
                migrations.AddField(
                    model_name='kommuneconfig',
                    name='tooltip_eierbrok',
                    field=models.TextField(blank=True, default='Eierandel uttrykt som brøkdel av eiendommen.', help_text='Vises ved siden av «Eierbrøk» i eiendomskortet.'),
                ),
                migrations.AddField(
                    model_name='kommuneconfig',
                    name='tooltip_fnr',
                    field=models.TextField(blank=True, default='Nummer for festetomt under gårdsnummeret.', help_text='Vises ved siden av «Festenummer» i eiendomskortet.'),
                ),
                migrations.AddField(
                    model_name='kommuneconfig',
                    name='tooltip_gnr',
                    field=models.TextField(blank=True, default='Hovednummer som identifiserer gården i matrikkelen.', help_text='Vises ved siden av «Gårdsnummer» i eiendomskortet.'),
                ),
                migrations.AddField(
                    model_name='kommuneconfig',
                    name='tooltip_property_area',
                    field=models.TextField(blank=True, default='Totalt registrert areal for eiendommen.', help_text='Vises ved siden av «Eiendomsareal» i eiendomskortet.'),
                ),
                migrations.AddField(
                    model_name='kommuneconfig',
                    name='tooltip_snr',
                    field=models.TextField(blank=True, default='Nummer som identifiserer seksjonen i en seksjonert eiendom.', help_text='Vises ved siden av «Seksjonsnummer» i eiendomskortet.'),
                ),
            ],
        ),
    ]
