# Generated by Django 5.1.7 on 2026-03-16 09:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_replace_opening_hours_with_daily_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kommuneconfig',
            name='opening_hours',
            field=wagtail.fields.StreamField([('periode', 4)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Mandag', 'Mandag'), ('Tirsdag', 'Tirsdag'), ('Onsdag', 'Onsdag'), ('Torsdag', 'Torsdag'), ('Fredag', 'Fredag'), ('Lørdag', 'Lørdag'), ('Søndag', 'Søndag')], 'label': 'Fra dag'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Mandag', 'Mandag'), ('Tirsdag', 'Tirsdag'), ('Onsdag', 'Onsdag'), ('Torsdag', 'Torsdag'), ('Fredag', 'Fredag'), ('Lørdag', 'Lørdag'), ('Søndag', 'Søndag')], 'label': 'Til dag'}), 2: ('wagtail.blocks.TimeBlock', (), {'label': 'Åpner'}), 3: ('wagtail.blocks.TimeBlock', (), {'label': 'Stenger'}), 4: ('wagtail.blocks.StructBlock', [[('fra_dag', 0), ('til_dag', 1), ('apner', 2), ('stenger', 3)]], {'label': 'Åpningstid'})}),
        ),
    ]
